# This is a config for E2B sandbox template.
# You can use template ID (g2t3wl8dyxr317pjif7i) or template name (mkinf-io__browser-use-gologin) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("mkinf-io__browser-use-gologin") # Sync sandbox
# sandbox = await AsyncSandbox.create("mkinf-io__browser-use-gologin") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('mkinf-io__browser-use-gologin')

team_id = "6154833f-d6de-4abb-929b-c580b082ebf9"
start_cmd = "/entrypoint.sh"
dockerfile = "e2b.Dockerfile"
template_name = "mkinf-io__browser-use-gologin"
template_id = "g2t3wl8dyxr317pjif7i"
